# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('meme_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_profile', to='socialaccount.SocialAccount'),
        ),
    ]
