# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_feed', '0003_auto_20171204_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='display_name',
        ),
    ]
