# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_feed', '0004_remove_author_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
