# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_feed', '0005_author_name_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
