# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_feed', '0007_authorcomment_authorlike_grouppostcomment_grouppostlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorlike',
            old_name='added',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='grouppost',
            old_name='creation',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='grouppostlike',
            old_name='added',
            new_name='created',
        ),
    ]
