# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_feed', '0008_auto_20171209_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorcomment',
            old_name='added',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='grouppostcomment',
            old_name='added',
            new_name='created',
        ),
    ]
