# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meme_feed', '0009_auto_20171209_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group_id', models.CharField(max_length=100)),
                ('_facebook_auth_key', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='grouppost',
            name='facebook_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='meme_feed.FacebookGroup'),
            preserve_default=False,
        ),
    ]
