# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_feed', '0010_auto_20171215_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookgroup',
            name='group_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
