# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import meme_feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_feed', '0011_auto_20171215_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookgroup',
            name='_criteria_last_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='_criteria_last_value',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='_minimal_quality_factor',
            field=models.FloatField(default=0.85, validators=[meme_feed.models.validate_minimal_quality_factor]),
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='deep_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
