# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_feed', '0012_auto_20171216_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookgroup',
            name='_criteria_last_updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='_criteria_last_value',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='_facebook_auth_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
