# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_feed', '0013_auto_20171216_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookgroup',
            name='deep_validated',
            field=models.BooleanField(default=False),
        ),
    ]
